query Posts($after: String, $before: String, $first: Int, $last: Int) {
  postsConnection(after: $after, before: $before, first: $first, last: $last) {
    posts: edges {
      node {
        author {
          name
        }
        title
        excerpt
        slug
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
  }
}
